"""add image_url to Court

Revision ID: 773c9ea1de7a
Revises: 
Create Date: 2025-09-10 00:00:46.570818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773c9ea1de7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
